<?php $__env->startSection('content'); ?>
    <?php echo $__env->make('admin.employees.modals.index', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
    <?php echo $__env->make('admin.toast.toast', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
    <?php echo $__env->make('admin.delete.deletemodal', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
            
                
                    
                        
                            
                                
                                    
                                
                            
                            
                            
                                
                                    
                                        
                                        
                                            
                                            
                                            
                                                
                                        
                                                
                                                    
                                                        
                                                        
                                                    
                                                
                                    
                                            
                                        
                                        


                                        
                                            
                                            
                                            
                                                
                                        
                                                
                                                    
                                                        
                                                        
                                                    
                                                
                                    
                                            
                                        

                                        
                                            
                                            
                                        

                                    
                                
                            
                        
                    
                
            




<?php $__env->stopSection(); ?>
<?php echo $__env->make('landing.landing', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>